// angular/src/app/pages/refunds.ts
import {
  Component,
  DestroyRef,
  OnInit,
  TemplateRef,
  ViewChild,
  inject,
} from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { EMPTY, Subject, catchError, from, startWith, switchMap } from 'rxjs';

import { AuditLog } from '../shared/audit-log';
import { Button } from '../shared/button';
import { Card } from '../shared/card';
import { Modal, ModalFooter } from '../shared/modal';
import { StatusBadge } from '../shared/status-badge';
import { Table, TableCellContext, TableColumn } from '../shared/table';
import { formatCurrency, formatDate } from '../lib/utils';
import { AuthService } from '../services/auth-service';
import { RefundService } from '../services/refund-service';
import { Payment, Refund, RefundAction } from '../types/refund';

interface RefundFilters {
  search: string;
  refundStatus: string;
  minAmount: string;
  maxAmount: string;
  risk: string;
}

@Component({
  selector: 'app-refunds',
  imports: [AuditLog, Button, Card, Modal, ModalFooter, StatusBadge, Table],
  templateUrl: './refunds.html',
})
export class Refunds implements OnInit {
  private readonly refundService = inject(RefundService);
  private readonly authService = inject(AuthService);
  private readonly destroyRef = inject(DestroyRef);
  private readonly filterChanges = new Subject<void>();

  @ViewChild('customerCell', { static: true })
  customerCell!: TemplateRef<TableCellContext<Payment>>;
  @ViewChild('amountCell', { static: true })
  amountCell!: TemplateRef<TableCellContext<Payment>>;
  @ViewChild('refundableCell', { static: true })
  refundableCell!: TemplateRef<TableCellContext<Payment>>;
  @ViewChild('refundHistoryCell', { static: true })
  refundHistoryCell!: TemplateRef<TableCellContext<Payment>>;
  @ViewChild('paymentDateCell', { static: true })
  paymentDateCell!: TemplateRef<TableCellContext<Payment>>;

  readonly currentUser = this.authService.currentUser;

  payments: Payment[] = [];
  loading = true;
  selectedPayment: Payment | null = null;
  refundModal = { isOpen: false, amount: '', reason: '' };
  actionModal: { isOpen: boolean; action: RefundAction; refundId: string } = {
    isOpen: false,
    action: 'approve',
    refundId: '',
  };
  notes = '';
  error: string | null = null;
  filters: RefundFilters = {
    search: '',
    refundStatus: '',
    minAmount: '',
    maxAmount: '',
    risk: '',
  };

  columns: TableColumn<Payment>[] = [];

  ngOnInit(): void {
    this.columns = [
      {
        key: 'id',
        header: 'Payment ID',
        className: 'font-medium',
      },
      {
        key: 'customerName',
        header: 'Customer',
        cell: this.customerCell,
      },
      {
        key: 'amount',
        header: 'Amount',
        cell: this.amountCell,
      },
      {
        key: 'refundableAmount',
        header: 'Refundable',
        cell: this.refundableCell,
      },
      {
        key: 'refundHistory',
        header: 'Refunds',
        cell: this.refundHistoryCell,
      },
      {
        key: 'paymentDate',
        header: 'Payment Date',
        cell: this.paymentDateCell,
      },
    ];

    this.filterChanges
      .pipe(
        startWith(undefined),
        switchMap(() => {
          this.loading = true;
          return from(
            this.refundService.getPayments({
              search: this.filters.search || undefined,
              refundStatus: this.filters.refundStatus || undefined,
              minAmount: this.filters.minAmount ? parseFloat(this.filters.minAmount) : undefined,
              maxAmount: this.filters.maxAmount ? parseFloat(this.filters.maxAmount) : undefined,
              risk: this.filters.risk || undefined,
            })
          ).pipe(
            catchError(() => {
              this.error = 'Failed to load payments';
              this.loading = false;
              return EMPTY;
            })
          );
        }),
        takeUntilDestroyed(this.destroyRef)
      )
      .subscribe(payments => {
        this.payments = payments;
        this.loading = false;
      });
  }

  loadPayments(): void {
    this.filterChanges.next();
  }

  updateFilter<K extends keyof RefundFilters>(key: K, value: string): void {
    this.filters = { ...this.filters, [key]: value };
    this.loadPayments();
  }

  async handleRequestRefund(): Promise<void> {
    const currentUser = this.currentUser();
    if (!this.selectedPayment || !currentUser) return;

    try {
      const amount = parseFloat(this.refundModal.amount);

      // Check authorization
      if (!this.authService.canRefundAmount(amount)) {
        this.error =
          'Support agents may only refund up to $500. Amounts above $500 require Finance admin approval.';
        return;
      }

      if (amount > this.selectedPayment.refundableAmount) {
        this.error = 'Refund amount exceeds refundable amount';
        return;
      }

      if (!this.refundModal.reason.trim()) {
        this.error = 'Please provide a reason for the refund';
        return;
      }

      await this.refundService.requestRefund(
        this.selectedPayment.id,
        amount,
        currentUser.id,
        currentUser.name,
        this.refundModal.reason
      );

      this.refundModal = { isOpen: false, amount: '', reason: '' };
      this.selectedPayment = null;
      this.error = null;
      this.loadPayments();
    } catch {
      this.error = 'Failed to request refund';
    }
  }

  async handleRefundAction(): Promise<void> {
    const currentUser = this.currentUser();
    if (!this.actionModal.refundId || !currentUser) return;

    try {
      if (!this.notes.trim()) {
        this.error = 'Please provide a reason for this action';
        return;
      }

      await this.refundService.processRefundAction(
        this.actionModal.refundId,
        this.actionModal.action,
        currentUser.id,
        currentUser.name,
        this.notes
      );

      this.actionModal = { isOpen: false, action: 'approve', refundId: '' };
      this.notes = '';
      this.selectedPayment = null;
      this.error = null;
      this.loadPayments();
    } catch {
      this.error = 'Failed to process action';
    }
  }

  openRefundModal(): void {
    if (!this.selectedPayment) return;
    this.refundModal = {
      isOpen: true,
      amount: this.selectedPayment.refundableAmount.toString(),
      reason: '',
    };
  }

  closeRefundModal(): void {
    this.refundModal = { isOpen: false, amount: '', reason: '' };
  }

  openActionModal(action: RefundAction, refundId: string): void {
    this.actionModal = { isOpen: true, action, refundId };
  }

  closeActionModal(): void {
    this.actionModal = { isOpen: false, action: 'approve', refundId: '' };
  }

  canRefundAmount(amount: number): boolean {
    return this.authService.canRefundAmount(amount);
  }

  /** Mirrors `disabled={!authService.canRefundAmount(parseFloat(refundModal.amount) || 0)}`. */
  get requestRefundDisabled(): boolean {
    return !this.authService.canRefundAmount(parseFloat(this.refundModal.amount) || 0);
  }

  get requestRefundOverLimit(): boolean {
    return parseFloat(this.refundModal.amount) > 500 && this.currentUser()?.role === 'support';
  }

  get requestRefundBlockedByLimit(): boolean {
    return (
      !!this.selectedPayment &&
      this.selectedPayment.refundableAmount > 500 &&
      this.currentUser()?.role === 'support'
    );
  }

  get actionModalRefund(): Refund | undefined {
    return this.selectedPayment?.refundHistory.find(r => r.id === this.actionModal.refundId);
  }

  get actionModalTitle(): string {
    return `${this.formatAction(this.actionModal.action)} Refund`;
  }

  get actionModalActionLabel(): string {
    return this.actionModal.action.replace(/_/g, ' ');
  }

  /** Mirrors the compound `disabled` expression on the action modal's confirm button. */
  get actionConfirmDisabled(): boolean {
    if (this.actionModal.action !== 'approve') return false;
    const refund = this.actionModalRefund;
    if (!refund) return false;
    return !this.authService.canRefundAmount(refund.amount);
  }

  get actionModalOverLimit(): boolean {
    if (this.actionModal.action !== 'approve') return false;
    const refund = this.actionModalRefund;
    return !!refund && !this.authService.canRefundAmount(refund.amount);
  }

  formatCurrency(amount: number, currency?: string): string {
    return formatCurrency(amount, currency);
  }

  formatDate(date: Date): string {
    return formatDate(date);
  }

  private formatAction(action: string): string {
    return action.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
  }
}

// app/refunds/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { Payment, RefundAction } from '@/types/refund';
import { refundService } from '@/services/refund-service';
import { authService } from '@/lib/auth';
import { Card } from '@/components/shared/Card';
import { Table } from '@/components/shared/Table';
import { StatusBadge } from '@/components/shared/StatusBadge';
import { Button } from '@/components/shared/Button';
import { Modal } from '@/components/shared/Modal';
import { AuditLog } from '@/components/shared/AuditLog';
import { formatDate, formatCurrency } from '@/lib/utils';

export default function RefundsPage() {
  const [payments, setPayments] = useState<Payment[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedPayment, setSelectedPayment] = useState<Payment | null>(null);
  const [refundModal, setRefundModal] = useState({ isOpen: false, amount: '', reason: '' });
  const [actionModal, setActionModal] = useState<{ isOpen: boolean; action: RefundAction; refundId: string }>({ isOpen: false, action: 'approve', refundId: '' });
  const [notes, setNotes] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [filters, setFilters] = useState({
    search: '',
    refundStatus: '',
    minAmount: '',
    maxAmount: '',
    risk: ''
  });
  const [currentUser, setCurrentUser] = useState(authService.getCurrentUser());

  useEffect(() => {
    const unsubscribe = authService.subscribe((user) => {
      setCurrentUser(user);
    });
    return unsubscribe;
  }, []);

  useEffect(() => {
    loadPayments();
  }, [filters]);

  const loadPayments = async () => {
    try {
      setLoading(true);
      const data = await refundService.getPayments({
        search: filters.search || undefined,
        refundStatus: filters.refundStatus || undefined,
        minAmount: filters.minAmount ? parseFloat(filters.minAmount) : undefined,
        maxAmount: filters.maxAmount ? parseFloat(filters.maxAmount) : undefined,
        risk: filters.risk || undefined
      });
      setPayments(data);
    } catch (err) {
      setError('Failed to load payments');
    } finally {
      setLoading(false);
    }
  };

  const handleRequestRefund = async () => {
    if (!selectedPayment || !currentUser) return;

    try {
      const amount = parseFloat(refundModal.amount);
      
      // Check authorization
      if (!authService.canRefundAmount(amount)) {
        setError('Support agents may only refund up to $500. Amounts above $500 require Finance admin approval.');
        return;
      }

      if (amount > selectedPayment.refundableAmount) {
        setError('Refund amount exceeds refundable amount');
        return;
      }

      if (!refundModal.reason.trim()) {
        setError('Please provide a reason for the refund');
        return;
      }

      await refundService.requestRefund(
        selectedPayment.id,
        amount,
        currentUser.id,
        currentUser.name,
        refundModal.reason
      );

      setRefundModal({ isOpen: false, amount: '', reason: '' });
      setSelectedPayment(null);
      setError(null);
      loadPayments();
    } catch (err) {
      setError('Failed to request refund');
    }
  };

  const handleRefundAction = async () => {
    if (!actionModal.refundId || !currentUser) return;

    try {
      if (!notes.trim()) {
        setError('Please provide a reason for this action');
        return;
      }

      await refundService.processRefundAction(
        actionModal.refundId,
        actionModal.action,
        currentUser.id,
        currentUser.name,
        notes
      );

      setActionModal({ isOpen: false, action: 'approve', refundId: '' });
      setNotes('');
      setSelectedPayment(null);
      setError(null);
      loadPayments();
    } catch (err) {
      setError('Failed to process action');
    }
  };

  const columns = [
    {
      key: 'id',
      header: 'Payment ID',
      className: 'font-medium'
    },
    {
      key: 'customerName',
      header: 'Customer',
      render: (value: string, row: Payment) => (
        <div>
          <p className="font-medium">{value}</p>
          <p className="text-xs text-gray-500">{row.customerEmail}</p>
        </div>
      )
    },
    {
      key: 'amount',
      header: 'Amount',
      render: (value: number, row: Payment) => formatCurrency(value, row.currency)
    },
    {
      key: 'refundableAmount',
      header: 'Refundable',
      render: (value: number, row: Payment) => formatCurrency(value, row.currency)
    },
    {
      key: 'refundHistory',
      header: 'Refunds',
      render: (value: any[]) => (
        <span className="text-sm text-gray-600">{value.length} request(s)</span>
      )
    },
    {
      key: 'paymentDate',
      header: 'Payment Date',
      render: (value: Date) => formatDate(value)
    }
  ];

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-gray-500">Loading payments...</div>
      </div>
    );
  }

  return (
    <div>
      <h1 className="text-2xl font-bold text-gray-900 mb-6">Refunds Dashboard</h1>

      {error && (
        <div className="mb-4 p-4 bg-red-50 border border-red-200 rounded-lg text-red-700">
          {error}
        </div>
      )}

      <Card className="mb-6">
        <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
          <input
            type="text"
            placeholder="Search by customer, ID..."
            value={filters.search}
            onChange={(e) => setFilters({ ...filters, search: e.target.value })}
            className="px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
          <select
            value={filters.refundStatus}
            onChange={(e) => setFilters({ ...filters, refundStatus: e.target.value })}
            className="px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            <option value="">All Statuses</option>
            <option value="pending">Pending</option>
            <option value="approved">Approved</option>
            <option value="rejected">Rejected</option>
            <option value="processed">Processed</option>
          </select>
          <input
            type="number"
            placeholder="Min Amount"
            value={filters.minAmount}
            onChange={(e) => setFilters({ ...filters, minAmount: e.target.value })}
            className="px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
          <input
            type="number"
            placeholder="Max Amount"
            value={filters.maxAmount}
            onChange={(e) => setFilters({ ...filters, maxAmount: e.target.value })}
            className="px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
          <select
            value={filters.risk}
            onChange={(e) => setFilters({ ...filters, risk: e.target.value })}
            className="px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            <option value="">All Risk Levels</option>
            <option value="low">Low</option>
            <option value="medium">Medium</option>
            <option value="high">High</option>
          </select>
        </div>
      </Card>

      <Card>
        <Table data={payments} columns={columns} onRowClick={setSelectedPayment} />
      </Card>

      {selectedPayment && (
        <Modal
          isOpen={!!selectedPayment}
          onClose={() => setSelectedPayment(null)}
          title={`Payment: ${selectedPayment.id}`}
          size="lg"
        >
          <div className="space-y-6">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <p className="text-sm font-medium text-gray-500">Customer</p>
                <p className="text-lg font-semibold">{selectedPayment.customerName}</p>
                <p className="text-sm text-gray-600">{selectedPayment.customerEmail}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-500">Amount</p>
                <p className="text-lg font-semibold">{formatCurrency(selectedPayment.amount, selectedPayment.currency)}</p>
                <p className="text-sm text-gray-600">Refundable: {formatCurrency(selectedPayment.refundableAmount, selectedPayment.currency)}</p>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4 text-sm">
              <div>
                <span className="text-gray-500">Transaction ID:</span>
                <span className="ml-2 font-medium">{selectedPayment.transactionId}</span>
              </div>
              <div>
                <span className="text-gray-500">Payment Date:</span>
                <span className="ml-2 font-medium">{formatDate(selectedPayment.paymentDate)}</span>
              </div>
            </div>

            {selectedPayment.refundHistory.length > 0 && (
              <div>
                <p className="text-sm font-medium text-gray-500 mb-2">Refund History</p>
                <div className="space-y-3">
                  {selectedPayment.refundHistory.map((refund) => (
                    <div key={refund.id} className="bg-gray-50 p-4 rounded-lg">
                      <div className="flex justify-between items-start mb-2">
                        <div>
                          <p className="font-medium">{formatCurrency(refund.amount, selectedPayment.currency)}</p>
                          <p className="text-sm text-gray-600">{refund.reason}</p>
                        </div>
                        <StatusBadge status={refund.status} />
                      </div>
                      <div className="text-xs text-gray-500">
                        Requested by {refund.requestedBy} on {formatDate(refund.requestedAt)}
                      </div>
                      {refund.status === 'pending' && currentUser && (
                        <div className="flex gap-2 mt-3">
                          <Button
                            size="sm"
                            onClick={() => setActionModal({ isOpen: true, action: 'approve', refundId: refund.id })}
                            disabled={!authService.canRefundAmount(refund.amount)}
                          >
                            Approve
                          </Button>
                          <Button
                            variant="danger"
                            size="sm"
                            onClick={() => setActionModal({ isOpen: true, action: 'reject', refundId: refund.id })}
                          >
                            Reject
                          </Button>
                        </div>
                      )}
                      {refund.auditHistory.length > 0 && (
                        <details className="mt-2">
                          <summary className="text-xs text-blue-600 cursor-pointer">View Audit History</summary>
                          <AuditLog events={refund.auditHistory} className="mt-2" />
                        </details>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {selectedPayment.refundableAmount > 0 && (
              <div className="pt-4 border-t">
                <Button
                  onClick={() => setRefundModal({ isOpen: true, amount: selectedPayment.refundableAmount.toString(), reason: '' })}
                  disabled={selectedPayment.refundableAmount > 500 && currentUser?.role === 'support'}
                >
                  Request Refund
                </Button>
              </div>
            )}

            {selectedPayment.refundableAmount > 500 && currentUser?.role === 'support' && (
              <p className="text-sm text-orange-600 bg-orange-50 p-3 rounded-lg">
                ⚠️ Refunds above $500 require Finance admin approval
              </p>
            )}
          </div>
        </Modal>
      )}

      <Modal
        isOpen={refundModal.isOpen}
        onClose={() => setRefundModal({ isOpen: false, amount: '', reason: '' })}
        title="Request Refund"
        footer={
          <>
            <Button variant="secondary" onClick={() => setRefundModal({ isOpen: false, amount: '', reason: '' })}>
              Cancel
            </Button>
            <Button 
              onClick={handleRequestRefund}
              disabled={!authService.canRefundAmount(parseFloat(refundModal.amount) || 0)}
            >
              Request Refund
            </Button>
          </>
        }
      >
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Refund Amount (Max: {selectedPayment && formatCurrency(selectedPayment.refundableAmount)})
            </label>
            <input
              type="number"
              value={refundModal.amount}
              onChange={(e) => setRefundModal({ ...refundModal, amount: e.target.value })}
              max={selectedPayment?.refundableAmount}
              min="0"
              step="0.01"
              className="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
            {parseFloat(refundModal.amount) > 500 && currentUser?.role === 'support' && (
              <p className="text-sm text-orange-600 mt-1">
                ⚠️ Support agents may only refund up to $500
              </p>
            )}
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Reason
            </label>
            <textarea
              value={refundModal.reason}
              onChange={(e) => setRefundModal({ ...refundModal, reason: e.target.value })}
              placeholder="Enter refund reason..."
              rows={3}
              className="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>
        </div>
      </Modal>

      <Modal
        isOpen={actionModal.isOpen}
        onClose={() => setActionModal({ isOpen: false, action: 'approve', refundId: '' })}
        title={`${actionModal.action.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())} Refund`}
        footer={
          <>
            <Button variant="secondary" onClick={() => setActionModal({ isOpen: false, action: 'approve', refundId: '' })}>
              Cancel
            </Button>
            <Button 
              onClick={handleRefundAction}
              disabled={
                actionModal.action === 'approve' && 
                selectedPayment?.refundHistory.find(r => r.id === actionModal.refundId) &&
                !authService.canRefundAmount(selectedPayment.refundHistory.find(r => r.id === actionModal.refundId)?.amount || 0)
              }
            >
              Confirm
            </Button>
          </>
        }
      >
        <div>
          <p className="text-sm text-gray-600 mb-4">
            Please provide a reason for {actionModal.action.replace(/_/g, ' ')} this refund.
          </p>
          {actionModal.action === 'approve' && selectedPayment?.refundHistory.find(r => r.id === actionModal.refundId) && (
            <div className="mb-4">
              {(() => {
                const refund = selectedPayment.refundHistory.find(r => r.id === actionModal.refundId);
                if (refund && !authService.canRefundAmount(refund.amount)) {
                  return (
                    <p className="text-sm text-orange-600 bg-orange-50 p-3 rounded-lg">
                      ⚠️ Support agents may only refund up to $500
                    </p>
                  );
                }
                return null;
              })()}
            </div>
          )}
          <textarea
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            placeholder="Enter your notes..."
            rows={4}
            className="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
        </div>
      </Modal>
    </div>
  );
}
